### PR TITLE
#R8FED2

### PR DESCRIPTION
**Pull request by mc1098**
Trade page which gives the current trades. 
Trades can't be viewed when going directly to the URL unless logged in. 
Minimal UI implementation at present

### CODE REVIEW

**Comment by mc1098** [comment]
[R8FED2: Save pre-trade list to traded list](https://trello.com/c/GlFiB9cD/51-r8fed2-save-pre-trade-list-to-traded-list)

**Comment by mc1098** [comment]
@DA-Wishart There is no mock data for trades so -
if you want to test the trade list quickly you can login with my information as yours does not have any trades. 
You could also run through the whole thing adding a trade then viewing it.

**Comment by DeeDoubleYous** [comment]
this was more for the last pull request, but the redirects didn't work with the 'Fizzit-0.1/' added in front of the page name. Removing them redirects to the page properly.

**Comment by mc1098** [comment]
with '/Fizzit.com/...' prefix you mean? 
Does this problem still exist in this PR?

**Comment by DeeDoubleYous** [comment]
it does, 'Fizzit.com' doesn't point anywhere, its still Fizzit-0.1

**Comment by mc1098** [comment]
Okay thanks! 
Think this might be to do with how my IDE deploys and changes the war file to 'Fizzit.com'. 
I'll have to look at manually deploying it and see if I get the same issue

**Comment by mc1098** [comment]
Sorry for the delay! 
Nice one line change and maven packaging should produce a war file as 'Fizzit.com' so the url redirection should work for you now.

**Pull request merged**
