### PR TITLE
Barcode input

### PR DESCRIPTION
**Pull request by mc1098**
This pull request should satisfy our first two requirements in the most simple way, as discussed. 
The index.xhtml is JSF and the Java code uses CDI over Faces syntax, such as "Named" instead of "@ManagedBean" as the latter is being deprecated.
It does not attempt to seek the products from the barcode, and the barcode is validated in the simplest of ways (i.e. no check sums).

### CODE REVIEW

**Comment by DA-Wishart** [comment]
I don't know if its my issue, but there seems to be trouble getting javax.faces for use

**Comment by DeeDoubleYous** [comment]
~~With the pom file as it is, maven on my end fails to package it up. But by changing the javax dependency to provided rather than test the war file can be generated.~~
Also does this rely on some config changes in glassfish/tomcat, because when I try to deploy to glassfish I am receiving this error 
`/index.xhtml @25,65 <f:validator> A validator id was not specified. Typically the validator id is set in the constructor ValidateHandler(ValidatorConfig)`
and tomcat seems unable to load it at all.

**Comment by mc1098** [comment]
> ~With the pom file as it is, maven on my end fails to package it up. But by changing the javax dependency to provided rather than test the war file can be generated.~
> Also does this rely on some config changes in glassfish/tomcat, because when I try to deploy to glassfish I am receiving this error
> `/index.xhtml @25,65 <f:validator> A validator id was not specified. Typically the validator id is set in the constructor ValidateHandler(ValidatorConfig)`
> and tomcat seems unable to load it at all.

I take that the crossed out section doesn't apply anymore? 
I found the same problem when tried to package and deploy this code on my laptop (linux) and took me awhile to realise what went wrong! 
The code uses updated bean management, hence Named instead of @ManagedBean, and Glassfish 5.0 doesn't seem to handle this correctly but Glassfish 5.1 does! I forgot that I downloaded the most recent version on my PC and not my laptop. 
So downloading 5.1 on my laptop and redeploying worked correctly!
Sorry about this..🤦‍♂

**Comment by DeeDoubleYous** [comment]
Yeah the crossed out bit is no longer applicable, re-cloned the fork to make sure the issue I got was actually happening. And the update to 5.1 does work. Looks really good.

**Review by DeeDoubleYous — APPROVED** [review]
Satisfies the first 2 objectives,

**Pull request merged**
