### PR TITLE
R14 email confirmation

### PR DESCRIPTION
**Pull request by mc1098**
This PR includes an email JSF page which is generated using a query parameter when you are signed in. It's a bit of hack but I think for showing what a generated email is this is an okay solution without worrying about using an SMTP server (real or fake). 

So to view an email you'd need to login with Fizzit then got to "/Fizzit.com/email.jsf?trade=:tradeId" 
where ":tradeId" is the particular trade id you want to generate the email for. It doesn't filter out trades where the status doesn't make sense, like cancelled, but for a mock I think this is okay?

### CODE REVIEW

**Comment by mc1098** [comment]
[R14BED1: Email integration](https://trello.com/c/srTuXa0w/62-r14bed1-email-integration)

**Comment by DeeDoubleYous** [comment]
In this it seems that the confirm trade button only works when there is a vlaue in the barcode input box, Otherwise when it says that there is a barcode validation issue.

**Comment by mc1098** [comment]
Oh I though I fixed that previously as I remember coming across the same thing! It needs to be fixed but this PR doesn't change anything on the index.xhtml page so doesn't apply here. I'll flag it as an issue though. 
Does the rest of it work for you?

**Comment by DeeDoubleYous** [comment]
ok, sorry if this sounds dumb, I'm in the last few days of the diseases, but the implementation of the email is purely prototype? Its just when I try and navigate to it I get an error.
image

**Comment by mc1098** [comment]
What URL are you using to access it?

**Comment by DeeDoubleYous** [comment]
image

**Comment by mc1098** [comment]
Oh yeah so you need to give the page the order number.
so for order 17 you would use "localhost:8080/Fizzit.com/email.xhtml?trade=17" 
It is a prototype but could make it pull up an error or redirect if no query params are given.

**Comment by DeeDoubleYous** [comment]
ah there we go, all good

**Pull request merged**
