### PR TITLE
Initial web application with maven.

### PR DESCRIPTION
**Pull request by mc1098**
Uses JDK 8 to support development in the labs. 
Mostly generated files and directories with a simple "hello world" 
index page which will help us test deployment.

Deleted the blank document too.

What do you think of this as the initial point for our project?

### CODE REVIEW

**Comment by DeeDoubleYous** [comment]
I'll have a glance at it when I get home.

**Comment by DeeDoubleYous** [comment]
As a starting point it is good yeah

**Review by DeeDoubleYous — APPROVED** [review]

**Comment by mc1098** [comment]
[Set up workspace](https://trello.com/c/x3BS1qeb/7-set-up-workspace)

**Comment by mc1098** [comment]
[S1BED1: Configure Java War Application with Maven](https://trello.com/c/JvfB5oah/20-s1bed1-configure-java-war-application-with-maven)

**Comment by mc1098** [comment]
[R1FED1: Create home/index page](https://trello.com/c/ozNsWfDD/22-r1fed1-create-home-index-page)

**Pull request merged**
